# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        docker build . -t landorphancontainers.azurecr.io/landorphan/dotnet/core/sdk:latest
      displayName: Build Docker Image
    - task: Docker@2
      displayName: Push to Azure Registry
      inputs:
        containerRegistry: 'LandorphanDocker'
        repository: 'landorphan/dotnet/core/sdk'
        command: 'push'
        tags: 'latest'
    - task: Docker@2
      displayName: Push to DockerHub Registry
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'landorphan/dotnet/core/sdk'
        command: 'push'
        tags: 'latest'
