# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          landorphan/dotnet/core/sdk:3.1-bionic
    - task: Docker@2
      inputs:
        containerRegistry: 'LandorphanDocker'
        repository: 'landorphan/dotnet/core/sdk'
        command: 'push'
        tags: 'landorphan/dotnet/core/sdk:3.1-bionic'
