# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        docker build . \
          -t landorphancontainers.azurecr.io/landorphan/dotnet/core/sdk:3.1-bionic
          # -t landorphan/dotnet/core/sdk:3.1-bionic \
      displayName: Build Docker Image
    - task: Docker@2
      displayName: Push to (Landorphan) Azure Container Regsitry
      inputs:
        containerRegistry: 'LandorphanDocker'
        repository: 'landorphancontainers.azurecr.io/landorphan/dotnet/core/sdk'
        command: 'push'
        tags: 'landorphancontainers.azurecr.io/landorphan/dotnet/core/sdk:3.1-bionic'
